import sqlite3
conn = sqlite3.connect("/root/skillbazaar/backend/data/skillbazaar.db")
c = conn.cursor()

c.execute('SELECT COUNT(*) FROM products WHERE status="active"')
print('Products:', c.fetchone()[0])
c.execute('SELECT category, COUNT(*) FROM products WHERE status="active" GROUP BY category')
print('By category:', c.fetchall())
c.execute('SELECT COUNT(*) FROM bounties')
print('Bounties:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM users WHERE username IS NOT NULL')
print('Named users:', c.fetchone()[0])
c.execute('SELECT id,username,nickname FROM users WHERE username IN ("quant_alice","llm_bob","dev_charlie","security_eve","product_frank","api_judy")')
print('Key NPCs:', c.fetchall())
c.execute('SELECT COUNT(*) FROM licenses')
print('Licenses:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM transactions')
print('Transactions:', c.fetchone()[0])
c.execute('PRAGMA table_info(user_profiles)')
print('Profile cols:', [r[1] for r in c.fetchall()])
c.execute('PRAGMA table_info(licenses)')
print('License cols:', [r[1] for r in c.fetchall()])
c.execute('PRAGMA table_info(transactions)')
print('Transaction cols:', [r[1] for r in c.fetchall()])
